const errFunc = () => {
    throw new Error('error was thrown');
}

module.exports = {errFunc}